/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as SplatRouteImport } from './pages/$'
import { Route as AppRouteImport } from './pages/_app'
import { Route as AuthRouteImport } from './pages/_auth'
import { Route as NoAccessRouteImport } from './pages/no-access'
import { Route as ResetPasswordRouteImport } from './pages/reset-password'
import { Route as VerifyEmailRouteImport } from './pages/verify-email'
import { Route as AppActivityRouteImport } from './pages/_app/activity'
import { Route as AppDeliverabilityRouteImport } from './pages/_app/deliverability'
import { Route as AppOnboardingRouteImport } from './pages/_app/onboarding'
import { Route as AppOverviewRouteImport } from './pages/_app/overview'
import { Route as AppProfileRouteImport } from './pages/_app/profile'
import { Route as AppStaffRouteImport } from './pages/_app/staff'
import { Route as AppSuppressionsRouteImport } from './pages/_app/suppressions'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './pages/_auth/login'
import { Route as AuthRegisterRouteImport } from './pages/_auth/register'
import { Route as AuthCallbackRouteImport } from './pages/auth/callback'
import { Route as InvitationsAcceptRouteImport } from './pages/invitations/accept'
import { Route as AppEmailsIndexRouteImport } from './pages/_app/emails/index'
import { Route as AppEmailsEmailIdRouteImport } from './pages/_app/emails/$emailId'
import { Route as AppTenantsIndexRouteImport } from './pages/_app/tenants/index'
import { Route as AppTenantsTenantIdRouteImport } from './pages/_app/tenants/$tenantId'
import { Route as AppUsersIndexRouteImport } from './pages/_app/users/index'
import { Route as AppUsersUserIdRouteImport } from './pages/_app/users/$userId'
import { Route as AppTenantsTenantIdIndexRouteImport } from './pages/_app/tenants/$tenantId.index'
import { Route as AppTenantsTenantIdActivityRouteImport } from './pages/_app/tenants/$tenantId.activity'
import { Route as AppTenantsTenantIdEmailsRouteImport } from './pages/_app/tenants/$tenantId.emails'
import { Route as AppTenantsTenantIdInvitationsRouteImport } from './pages/_app/tenants/$tenantId.invitations'
import { Route as AppTenantsTenantIdMembersRouteImport } from './pages/_app/tenants/$tenantId.members'
import { Route as AppTenantsTenantIdOnboardingRouteImport } from './pages/_app/tenants/$tenantId.onboarding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliverabilityRoute = AppDeliverabilityRouteImport.update({
  id: '/deliverability',
  path: '/deliverability',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppressionsRoute = AppSuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEmailsIndexRoute = AppEmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailsEmailIdRoute = AppEmailsEmailIdRouteImport.update({
  id: '/emails/$emailId',
  path: '/emails/$emailId',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsIndexRoute = AppTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsTenantIdRoute = AppTenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsTenantIdIndexRoute = AppTenantsTenantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantsTenantIdRoute,
} as any)
const AppTenantsTenantIdActivityRoute =
  AppTenantsTenantIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppTenantsTenantIdRoute,
  } as any)
const AppTenantsTenantIdEmailsRoute =
  AppTenantsTenantIdEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AppTenantsTenantIdRoute,
  } as any)
const AppTenantsTenantIdInvitationsRoute =
  AppTenantsTenantIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AppTenantsTenantIdRoute,
  } as any)
const AppTenantsTenantIdMembersRoute =
  AppTenantsTenantIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppTenantsTenantIdRoute,
  } as any)
const AppTenantsTenantIdOnboardingRoute =
  AppTenantsTenantIdOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppTenantsTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/activity': typeof AppActivityRoute
  '/deliverability': typeof AppDeliverabilityRoute
  '/onboarding': typeof AppOnboardingRoute
  '/overview': typeof AppOverviewRoute
  '/profile': typeof AppProfileRoute
  '/staff': typeof AppStaffRoute
  '/suppressions': typeof AppSuppressionsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/emails/$emailId': typeof AppEmailsEmailIdRoute
  '/tenants/$tenantId': typeof AppTenantsTenantIdRouteWithChildren
  '/users/$userId': typeof AppUsersUserIdRoute
  '/emails/': typeof AppEmailsIndexRoute
  '/tenants/': typeof AppTenantsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/tenants/$tenantId/activity': typeof AppTenantsTenantIdActivityRoute
  '/tenants/$tenantId/emails': typeof AppTenantsTenantIdEmailsRoute
  '/tenants/$tenantId/invitations': typeof AppTenantsTenantIdInvitationsRoute
  '/tenants/$tenantId/members': typeof AppTenantsTenantIdMembersRoute
  '/tenants/$tenantId/onboarding': typeof AppTenantsTenantIdOnboardingRoute
  '/tenants/$tenantId/': typeof AppTenantsTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/activity': typeof AppActivityRoute
  '/deliverability': typeof AppDeliverabilityRoute
  '/onboarding': typeof AppOnboardingRoute
  '/overview': typeof AppOverviewRoute
  '/profile': typeof AppProfileRoute
  '/staff': typeof AppStaffRoute
  '/suppressions': typeof AppSuppressionsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/emails/$emailId': typeof AppEmailsEmailIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/emails': typeof AppEmailsIndexRoute
  '/tenants': typeof AppTenantsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/tenants/$tenantId/activity': typeof AppTenantsTenantIdActivityRoute
  '/tenants/$tenantId/emails': typeof AppTenantsTenantIdEmailsRoute
  '/tenants/$tenantId/invitations': typeof AppTenantsTenantIdInvitationsRoute
  '/tenants/$tenantId/members': typeof AppTenantsTenantIdMembersRoute
  '/tenants/$tenantId/onboarding': typeof AppTenantsTenantIdOnboardingRoute
  '/tenants/$tenantId': typeof AppTenantsTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/deliverability': typeof AppDeliverabilityRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/suppressions': typeof AppSuppressionsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/_app/emails/$emailId': typeof AppEmailsEmailIdRoute
  '/_app/tenants/$tenantId': typeof AppTenantsTenantIdRouteWithChildren
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/emails/': typeof AppEmailsIndexRoute
  '/_app/tenants/': typeof AppTenantsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/tenants/$tenantId/activity': typeof AppTenantsTenantIdActivityRoute
  '/_app/tenants/$tenantId/emails': typeof AppTenantsTenantIdEmailsRoute
  '/_app/tenants/$tenantId/invitations': typeof AppTenantsTenantIdInvitationsRoute
  '/_app/tenants/$tenantId/members': typeof AppTenantsTenantIdMembersRoute
  '/_app/tenants/$tenantId/onboarding': typeof AppTenantsTenantIdOnboardingRoute
  '/_app/tenants/$tenantId/': typeof AppTenantsTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/no-access'
    | '/reset-password'
    | '/verify-email'
    | '/activity'
    | '/deliverability'
    | '/onboarding'
    | '/overview'
    | '/profile'
    | '/staff'
    | '/suppressions'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/invitations/accept'
    | '/emails/$emailId'
    | '/tenants/$tenantId'
    | '/users/$userId'
    | '/emails/'
    | '/tenants/'
    | '/users/'
    | '/tenants/$tenantId/activity'
    | '/tenants/$tenantId/emails'
    | '/tenants/$tenantId/invitations'
    | '/tenants/$tenantId/members'
    | '/tenants/$tenantId/onboarding'
    | '/tenants/$tenantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/no-access'
    | '/reset-password'
    | '/verify-email'
    | '/activity'
    | '/deliverability'
    | '/onboarding'
    | '/overview'
    | '/profile'
    | '/staff'
    | '/suppressions'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/invitations/accept'
    | '/emails/$emailId'
    | '/users/$userId'
    | '/emails'
    | '/tenants'
    | '/users'
    | '/tenants/$tenantId/activity'
    | '/tenants/$tenantId/emails'
    | '/tenants/$tenantId/invitations'
    | '/tenants/$tenantId/members'
    | '/tenants/$tenantId/onboarding'
    | '/tenants/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/_auth'
    | '/no-access'
    | '/reset-password'
    | '/verify-email'
    | '/_app/activity'
    | '/_app/deliverability'
    | '/_app/onboarding'
    | '/_app/overview'
    | '/_app/profile'
    | '/_app/staff'
    | '/_app/suppressions'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/auth/callback'
    | '/invitations/accept'
    | '/_app/emails/$emailId'
    | '/_app/tenants/$tenantId'
    | '/_app/users/$userId'
    | '/_app/emails/'
    | '/_app/tenants/'
    | '/_app/users/'
    | '/_app/tenants/$tenantId/activity'
    | '/_app/tenants/$tenantId/emails'
    | '/_app/tenants/$tenantId/invitations'
    | '/_app/tenants/$tenantId/members'
    | '/_app/tenants/$tenantId/onboarding'
    | '/_app/tenants/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  NoAccessRoute: typeof NoAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliverability': {
      id: '/_app/deliverability'
      path: '/deliverability'
      fullPath: '/deliverability'
      preLoaderRoute: typeof AppDeliverabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppressions': {
      id: '/_app/suppressions'
      path: '/suppressions'
      fullPath: '/suppressions'
      preLoaderRoute: typeof AppSuppressionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/emails/': {
      id: '/_app/emails/'
      path: '/emails'
      fullPath: '/emails/'
      preLoaderRoute: typeof AppEmailsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emails/$emailId': {
      id: '/_app/emails/$emailId'
      path: '/emails/$emailId'
      fullPath: '/emails/$emailId'
      preLoaderRoute: typeof AppEmailsEmailIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/': {
      id: '/_app/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AppTenantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/$tenantId': {
      id: '/_app/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AppTenantsTenantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/$tenantId/': {
      id: '/_app/tenants/$tenantId/'
      path: '/'
      fullPath: '/tenants/$tenantId/'
      preLoaderRoute: typeof AppTenantsTenantIdIndexRouteImport
      parentRoute: typeof AppTenantsTenantIdRoute
    }
    '/_app/tenants/$tenantId/activity': {
      id: '/_app/tenants/$tenantId/activity'
      path: '/activity'
      fullPath: '/tenants/$tenantId/activity'
      preLoaderRoute: typeof AppTenantsTenantIdActivityRouteImport
      parentRoute: typeof AppTenantsTenantIdRoute
    }
    '/_app/tenants/$tenantId/emails': {
      id: '/_app/tenants/$tenantId/emails'
      path: '/emails'
      fullPath: '/tenants/$tenantId/emails'
      preLoaderRoute: typeof AppTenantsTenantIdEmailsRouteImport
      parentRoute: typeof AppTenantsTenantIdRoute
    }
    '/_app/tenants/$tenantId/invitations': {
      id: '/_app/tenants/$tenantId/invitations'
      path: '/invitations'
      fullPath: '/tenants/$tenantId/invitations'
      preLoaderRoute: typeof AppTenantsTenantIdInvitationsRouteImport
      parentRoute: typeof AppTenantsTenantIdRoute
    }
    '/_app/tenants/$tenantId/members': {
      id: '/_app/tenants/$tenantId/members'
      path: '/members'
      fullPath: '/tenants/$tenantId/members'
      preLoaderRoute: typeof AppTenantsTenantIdMembersRouteImport
      parentRoute: typeof AppTenantsTenantIdRoute
    }
    '/_app/tenants/$tenantId/onboarding': {
      id: '/_app/tenants/$tenantId/onboarding'
      path: '/onboarding'
      fullPath: '/tenants/$tenantId/onboarding'
      preLoaderRoute: typeof AppTenantsTenantIdOnboardingRouteImport
      parentRoute: typeof AppTenantsTenantIdRoute
    }
  }
}

interface AppTenantsTenantIdRouteChildren {
  AppTenantsTenantIdActivityRoute: typeof AppTenantsTenantIdActivityRoute
  AppTenantsTenantIdEmailsRoute: typeof AppTenantsTenantIdEmailsRoute
  AppTenantsTenantIdInvitationsRoute: typeof AppTenantsTenantIdInvitationsRoute
  AppTenantsTenantIdMembersRoute: typeof AppTenantsTenantIdMembersRoute
  AppTenantsTenantIdOnboardingRoute: typeof AppTenantsTenantIdOnboardingRoute
  AppTenantsTenantIdIndexRoute: typeof AppTenantsTenantIdIndexRoute
}

const AppTenantsTenantIdRouteChildren: AppTenantsTenantIdRouteChildren = {
  AppTenantsTenantIdActivityRoute: AppTenantsTenantIdActivityRoute,
  AppTenantsTenantIdEmailsRoute: AppTenantsTenantIdEmailsRoute,
  AppTenantsTenantIdInvitationsRoute: AppTenantsTenantIdInvitationsRoute,
  AppTenantsTenantIdMembersRoute: AppTenantsTenantIdMembersRoute,
  AppTenantsTenantIdOnboardingRoute: AppTenantsTenantIdOnboardingRoute,
  AppTenantsTenantIdIndexRoute: AppTenantsTenantIdIndexRoute,
}

const AppTenantsTenantIdRouteWithChildren =
  AppTenantsTenantIdRoute._addFileChildren(AppTenantsTenantIdRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDeliverabilityRoute: typeof AppDeliverabilityRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStaffRoute: typeof AppStaffRoute
  AppSuppressionsRoute: typeof AppSuppressionsRoute
  AppEmailsEmailIdRoute: typeof AppEmailsEmailIdRoute
  AppTenantsTenantIdRoute: typeof AppTenantsTenantIdRouteWithChildren
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppEmailsIndexRoute: typeof AppEmailsIndexRoute
  AppTenantsIndexRoute: typeof AppTenantsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDeliverabilityRoute: AppDeliverabilityRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppStaffRoute: AppStaffRoute,
  AppSuppressionsRoute: AppSuppressionsRoute,
  AppEmailsEmailIdRoute: AppEmailsEmailIdRoute,
  AppTenantsTenantIdRoute: AppTenantsTenantIdRouteWithChildren,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppEmailsIndexRoute: AppEmailsIndexRoute,
  AppTenantsIndexRoute: AppTenantsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  NoAccessRoute: NoAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
